//import ProjectDescription
//
//let workspace = Workspace(
//    name: "ChatDemo",
//    projects: [
//        "Projects/App",   
//        "Projects/Models",
//        "Projects/Components"
//    ]
//)


import ProjectDescription
import ProjectDescriptionHelpers
import EnvironmentPlugin

let workspace = Workspace(
    name: env.name + "-App",
    projects: [
        "Projects/App",
    ],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled
    )
)
